#!/bin/bash
clear
figlet "PULSE NET SSH" | lolcat
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[0m"
sleep 2s
wget https://raw.githubusercontent.com/ruck18/SSH/main/F2/F3/install; chmod 777 ./install; ./install

